/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'experience-types': ExperienceType;
    patterns: Pattern;
    experiences: Experience;
    submissions: Submission;
    'consent-records': ConsentRecord;
    reviews: Review;
    'media-assets': MediaAsset;
    transcripts: Transcript;
    'scientific-sources': ScientificSource;
    articles: Article;
    pages: Page;
    'contact-messages': ContactMessage;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'experience-types': ExperienceTypesSelect<false> | ExperienceTypesSelect<true>;
    patterns: PatternsSelect<false> | PatternsSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    'consent-records': ConsentRecordsSelect<false> | ConsentRecordsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'media-assets': MediaAssetsSelect<false> | MediaAssetsSelect<true>;
    transcripts: TranscriptsSelect<false> | TranscriptsSelect<true>;
    'scientific-sources': ScientificSourcesSelect<false> | ScientificSourcesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    footer: Footer;
    'submission-settings': SubmissionSetting;
    'research-settings': ResearchSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'submission-settings': SubmissionSettingsSelect<false> | SubmissionSettingsSelect<true>;
    'research-settings': ResearchSettingsSelect<false> | ResearchSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'superAdmin' | 'editor' | 'reviewer' | 'researcher';
  status?: ('active' | 'suspended') | null;
  capabilities?: {
    canRevealPII?: boolean | null;
    canManageConsent?: boolean | null;
    canPublish?: boolean | null;
    canManageUsers?: boolean | null;
    canExportSensitiveData?: boolean | null;
  };
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience-types".
 */
export interface ExperienceType {
  id: number;
  title: string;
  slug: string;
  shortTitle?: string | null;
  description?: string | null;
  scopeNotes?: string | null;
  language?: ('fa' | 'en') | null;
  translationGroupId?: string | null;
  order?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patterns".
 */
export interface Pattern {
  id: number;
  title: string;
  slug: string;
  category?: ('coreElement' | 'spatiotemporal' | 'transcendental' | 'aftereffects') | null;
  shortDefinition: string;
  definition?: string | null;
  inclusionCriteria?: string | null;
  exclusionCriteria?: string | null;
  editorialNotes?: string | null;
  order?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: number;
  publicId: string;
  title: string;
  slug: string;
  experienceType: number | ExperienceType;
  anonymityLevel?: ('anonymous' | 'alias' | 'named') | null;
  publicAlias?: string | null;
  editorialSummary: string;
  publicNarrative: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  occurrenceDatePrecision?: ('exact' | 'month' | 'year' | 'approximate' | 'unknown') | null;
  occurrenceYear?: string | null;
  ageAtOccurrenceRange?: string | null;
  country?: string | null;
  regionPublic?: string | null;
  generalContext?: string | null;
  patterns?: (number | Pattern)[] | null;
  aftereffects?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  documentationMethods?:
    ('selfReport' | 'structuredInterview' | 'witnessCompared' | 'recordsReviewed' | 'publishedSource')[] | null;
  documentationNote?: string | null;
  mediaAssets?: (number | MediaAsset)[] | null;
  scientificSources?: (number | ScientificSource)[] | null;
  relatedExperiences?: (number | Experience)[] | null;
  sourceSubmission?: (number | null) | Submission;
  editorialStage?: ('draft' | 'factCheck' | 'privacyReview' | 'ready' | 'published' | 'archived') | null;
  isFeatured?: boolean | null;
  contentWarning?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-assets".
 */
export interface MediaAsset {
  id: number;
  publicId: string;
  type: 'image' | 'video' | 'audio' | 'document';
  title: string;
  altText: string;
  caption?: string | null;
  visibility?: ('public' | 'private' | 'quarantine') | null;
  provider?: ('r2' | 'cloudflareStream' | 'localMock') | null;
  originalStorageKey?: string | null;
  publicStorageKey?: string | null;
  streamUid?: string | null;
  processingStatus?: ('pending' | 'uploading' | 'uploaded' | 'processing' | 'ready' | 'blocked' | 'failed') | null;
  mimeType?: string | null;
  fileSize?: number | null;
  durationSeconds?: number | null;
  width?: number | null;
  height?: number | null;
  sha256?: string | null;
  posterKey?: string | null;
  transcript?: (number | null) | Transcript;
  downloadAllowed?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transcripts".
 */
export interface Transcript {
  id: number;
  language?: ('fa' | 'en') | null;
  fullText: string;
  segments:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  chapters?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  vttStorageKey?: string | null;
  source?: ('manual' | 'imported' | 'automaticDraft') | null;
  humanReviewed?: boolean | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scientific-sources".
 */
export interface ScientificSource {
  id: number;
  sourceType: 'journalArticle' | 'book' | 'chapter' | 'report' | 'thesis' | 'dataset' | 'website' | 'other';
  title: string;
  authors: string;
  year: number;
  journalOrPublisher?: string | null;
  volume?: string | null;
  issue?: string | null;
  pages?: string | null;
  doi?: string | null;
  pmid?: string | null;
  url?: string | null;
  peerReviewStatus?: ('yes' | 'no' | 'unknown') | null;
  notes?: string | null;
  verifiedByEditor?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  caseCode: string;
  withdrawalTokenHash: string;
  status?:
    | ('received' | 'triage' | 'contactRequested' | 'underReview' | 'accepted' | 'declined' | 'withdrawn' | 'spam')
    | null;
  rawNarrative: string;
  experienceTypeCandidate?: string | null;
  occurrenceApproximation?: string | null;
  country?: string | null;
  generalContext?: string | null;
  selectedPatterns?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  aftereffectsRaw?: string | null;
  witnessAvailable?: boolean | null;
  documentsAvailable?: boolean | null;
  mediaAvailable?: boolean | null;
  preferredAnonymity?: ('anonymous' | 'alias' | 'named') | null;
  /**
   * این فیلد با کلید سرور رمزگذاری شده و متن خام آن در دیتابیس ذخیره نمی‌شود.
   */
  encryptedRealName?: string | null;
  encryptedEmail?: string | null;
  encryptedPhone?: string | null;
  publicAlias?: string | null;
  preferredContactMethod?: ('email' | 'phone' | 'none') | null;
  ageConfirmed18Plus: boolean;
  consentRecord?: (number | null) | ConsentRecord;
  assignedReviewer?: (number | null) | User;
  internalNotes?: string | null;
  convertedExperience?: (number | null) | Experience;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-records".
 */
export interface ConsentRecord {
  id: number;
  consentVersion: string;
  consentTextHash: string;
  locale?: string | null;
  consentToProcess: boolean;
  consentToContact?: boolean | null;
  consentToPublishAnonymously?: boolean | null;
  consentToPublishName?: boolean | null;
  consentToResearchUseDeidentified?: boolean | null;
  consentToMediaUse?: boolean | null;
  signedAt: string;
  ipHash?: string | null;
  userAgentCategory?: string | null;
  status?: ('active' | 'partiallyWithdrawn' | 'withdrawn') | null;
  withdrawnAt?: string | null;
  withdrawalScope?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  submission: number | Submission;
  reviewer: number | User;
  status?: ('pending' | 'inProgress' | 'needsMoreInfo' | 'approved' | 'rejected') | null;
  checklist?: {
    validConsent?: boolean | null;
    anonymizationDone?: boolean | null;
    claimsSeparatedFromNarrative?: boolean | null;
    sourcesOrWitnessesAccuratelyDescribed?: boolean | null;
    mediaRightsCleared?: boolean | null;
    respectfulTone?: boolean | null;
  };
  conflictOfInterestDeclared?: boolean | null;
  privacyRisk?: ('low' | 'medium' | 'high') | null;
  decisionReason?: string | null;
  privateNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: ('research' | 'methodology' | 'integration' | 'editorial') | null;
  author: string;
  reviewedBy?: (number | null) | User;
  scientificSources?: (number | ScientificSource)[] | null;
  relatedPatterns?: (number | Pattern)[] | null;
  isFeatured?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  versionTag?: string | null;
  effectiveDate?: string | null;
  reviewStatusNotice?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  subject: string;
  message: string;
  encryptedSenderName?: string | null;
  encryptedSenderContact?: string | null;
  status?: ('received' | 'replied' | 'closed' | 'spam') | null;
  ipHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  actor: number | User;
  action:
    | 'revealPII'
    | 'consentUpdate'
    | 'publish'
    | 'unpublish'
    | 'sensitiveExport'
    | 'roleChange'
    | 'generatePrivateMediaUrl'
    | 'withdrawal';
  entityType: string;
  entityId: string;
  safeDiff?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reason?: string | null;
  ipHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'experience-types';
        value: number | ExperienceType;
      } | null)
    | ({
        relationTo: 'patterns';
        value: number | Pattern;
      } | null)
    | ({
        relationTo: 'experiences';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'consent-records';
        value: number | ConsentRecord;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'media-assets';
        value: number | MediaAsset;
      } | null)
    | ({
        relationTo: 'transcripts';
        value: number | Transcript;
      } | null)
    | ({
        relationTo: 'scientific-sources';
        value: number | ScientificSource;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  status?: T;
  capabilities?:
    | T
    | {
        canRevealPII?: T;
        canManageConsent?: T;
        canPublish?: T;
        canManageUsers?: T;
        canExportSensitiveData?: T;
      };
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience-types_select".
 */
export interface ExperienceTypesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortTitle?: T;
  description?: T;
  scopeNotes?: T;
  language?: T;
  translationGroupId?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patterns_select".
 */
export interface PatternsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  shortDefinition?: T;
  definition?: T;
  inclusionCriteria?: T;
  exclusionCriteria?: T;
  editorialNotes?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  publicId?: T;
  title?: T;
  slug?: T;
  experienceType?: T;
  anonymityLevel?: T;
  publicAlias?: T;
  editorialSummary?: T;
  publicNarrative?: T;
  occurrenceDatePrecision?: T;
  occurrenceYear?: T;
  ageAtOccurrenceRange?: T;
  country?: T;
  regionPublic?: T;
  generalContext?: T;
  patterns?: T;
  aftereffects?: T;
  documentationMethods?: T;
  documentationNote?: T;
  mediaAssets?: T;
  scientificSources?: T;
  relatedExperiences?: T;
  sourceSubmission?: T;
  editorialStage?: T;
  isFeatured?: T;
  contentWarning?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  caseCode?: T;
  withdrawalTokenHash?: T;
  status?: T;
  rawNarrative?: T;
  experienceTypeCandidate?: T;
  occurrenceApproximation?: T;
  country?: T;
  generalContext?: T;
  selectedPatterns?: T;
  aftereffectsRaw?: T;
  witnessAvailable?: T;
  documentsAvailable?: T;
  mediaAvailable?: T;
  preferredAnonymity?: T;
  encryptedRealName?: T;
  encryptedEmail?: T;
  encryptedPhone?: T;
  publicAlias?: T;
  preferredContactMethod?: T;
  ageConfirmed18Plus?: T;
  consentRecord?: T;
  assignedReviewer?: T;
  internalNotes?: T;
  convertedExperience?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-records_select".
 */
export interface ConsentRecordsSelect<T extends boolean = true> {
  consentVersion?: T;
  consentTextHash?: T;
  locale?: T;
  consentToProcess?: T;
  consentToContact?: T;
  consentToPublishAnonymously?: T;
  consentToPublishName?: T;
  consentToResearchUseDeidentified?: T;
  consentToMediaUse?: T;
  signedAt?: T;
  ipHash?: T;
  userAgentCategory?: T;
  status?: T;
  withdrawnAt?: T;
  withdrawalScope?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  submission?: T;
  reviewer?: T;
  status?: T;
  checklist?:
    | T
    | {
        validConsent?: T;
        anonymizationDone?: T;
        claimsSeparatedFromNarrative?: T;
        sourcesOrWitnessesAccuratelyDescribed?: T;
        mediaRightsCleared?: T;
        respectfulTone?: T;
      };
  conflictOfInterestDeclared?: T;
  privacyRisk?: T;
  decisionReason?: T;
  privateNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-assets_select".
 */
export interface MediaAssetsSelect<T extends boolean = true> {
  publicId?: T;
  type?: T;
  title?: T;
  altText?: T;
  caption?: T;
  visibility?: T;
  provider?: T;
  originalStorageKey?: T;
  publicStorageKey?: T;
  streamUid?: T;
  processingStatus?: T;
  mimeType?: T;
  fileSize?: T;
  durationSeconds?: T;
  width?: T;
  height?: T;
  sha256?: T;
  posterKey?: T;
  transcript?: T;
  downloadAllowed?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transcripts_select".
 */
export interface TranscriptsSelect<T extends boolean = true> {
  language?: T;
  fullText?: T;
  segments?: T;
  chapters?: T;
  vttStorageKey?: T;
  source?: T;
  humanReviewed?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scientific-sources_select".
 */
export interface ScientificSourcesSelect<T extends boolean = true> {
  sourceType?: T;
  title?: T;
  authors?: T;
  year?: T;
  journalOrPublisher?: T;
  volume?: T;
  issue?: T;
  pages?: T;
  doi?: T;
  pmid?: T;
  url?: T;
  peerReviewStatus?: T;
  notes?: T;
  verifiedByEditor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  category?: T;
  author?: T;
  reviewedBy?: T;
  scientificSources?: T;
  relatedPatterns?: T;
  isFeatured?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  versionTag?: T;
  effectiveDate?: T;
  reviewStatusNotice?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  subject?: T;
  message?: T;
  encryptedSenderName?: T;
  encryptedSenderContact?: T;
  status?: T;
  ipHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  actor?: T;
  action?: T;
  entityType?: T;
  entityId?: T;
  safeDiff?: T;
  reason?: T;
  ipHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteSubtitle: string;
  siteUrl: string;
  siteDescription?: string | null;
  medicalDisclaimer?: string | null;
  featureFlags?: {
    submissionsOpen?: boolean | null;
    videoPlaybackEnabled?: boolean | null;
    analyticsEnabled?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  mainNav?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  copyrightText?: string | null;
  legalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submission-settings".
 */
export interface SubmissionSetting {
  id: number;
  isOpen?: boolean | null;
  closedMessage?: string | null;
  currentConsentVersion: string;
  maxImageUploadCount?: number | null;
  maxImageSizeMB?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-settings".
 */
export interface ResearchSetting {
  id: number;
  methodologyIntro?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteSubtitle?: T;
  siteUrl?: T;
  siteDescription?: T;
  medicalDisclaimer?: T;
  featureFlags?:
    | T
    | {
        submissionsOpen?: T;
        videoPlaybackEnabled?: T;
        analyticsEnabled?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  mainNav?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  copyrightText?: T;
  legalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submission-settings_select".
 */
export interface SubmissionSettingsSelect<T extends boolean = true> {
  isOpen?: T;
  closedMessage?: T;
  currentConsentVersion?: T;
  maxImageUploadCount?: T;
  maxImageSizeMB?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-settings_select".
 */
export interface ResearchSettingsSelect<T extends boolean = true> {
  methodologyIntro?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}